FROM gatling:3.1.2

ARG MASTER_SERVER_PORT=8080
ARG AKKA_PORT=2551

ENV MASTER_SERVER_PORT=${MASTER_SERVER_PORT}
ENV AKKA_PORT=${AKKA_PORT}
ENV GATLING_PATH1="/opt/gatling-charts-highcharts-bundle"
ENV GATLING_PATH2="/usr/local/demdex/distGatling"

COPY gatling-*/*.sh /usr/local/demdex/distGatling/
RUN chmod +x /usr/local/demdex/distGatling/*.sh 
COPY gatling-*/target/*.jar /usr/local/demdex/distGatling/target/

EXPOSE ${MASTER_SERVER_PORT}
EXPOSE ${AKKA_PORT}
WORKDIR /usr/local/demdex/distGatling


CMD ["/bin/bash", "-c", "cd /usr/local/demdex/distGatling && ./master.sh -Dmaster.port=${AKKA_PORT} -Dmaster.kubernetes=true -Dserver.port=${MASTER_SERVER_PORT} -DCLUSTER_IP=`hostname -i` -DEXTERNAL_HOST=gatlingmaster-stage-akka.edge-stage.svc.cluster.local"]

