FROM gatling:3.1.2

ARG AGENT_SERVER_PORT=8090
ARG AKKA_PORT=8080
ARG LISTENING_AKKA_PORT=2556
ARG MASTER_SERVER=172.17.0.5


ENV AGENT_SERVER_PORT=${AGENT_SERVER_PORT}
ENV AKKA_PORT=${AKKA_PORT}
ENV MASTER_SERVER=${MASTER_SERVER}
ENV GATLING_PATH1="/opt/gatling-charts-highcharts-bundle"
ENV GATLING_PATH2="/usr/local/demdex/distGatling"


RUN mkdir -p /usr/local/demdex/distGatling/logs /usr/local/demdex/distGatling/uploads

COPY gatling-*/*.sh /usr/local/demdex/distGatling/
RUN chmod +x /usr/local/demdex/distGatling/*.sh 
COPY gatling-*/target/* /usr/local/demdex/distGatling/target/

#COPY cancel.sh /opt/gatling-charts-highcharts-bundle/bin/cancel.sh

EXPOSE ${AGENT_SERVER_PORT}
EXPOSE ${AKKA_PORT}
EXPOSE ${LISTENING_AKKA_PORT}

WORKDIR /usr/local/demdex/distGatling

CMD ["/bin/bash", "-c", "cd /usr/local/demdex/distGatling && ./agent.sh -Dakka.contact-points=${MASTER_SERVER}:2551 -Dactor.port=0 -Dserver.port=${AGENT_SERVER_PORT}"] -Dactor.numberOfActors=1
